# Generated by Django 3.2.2 on 2021-07-01 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rent', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('house_type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=100)),
                ('poste_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
