# Generated by Django 3.2.2 on 2021-07-01 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_house_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
