# Generated by Django 3.2.2 on 2021-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.FileField(upload_to='house_images'),
        ),
    ]
