# Generated by Django 3.2.2 on 2021-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
