# Generated by Django 3.2.2 on 2021-07-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20210701_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
