# Generated by Django 3.2.2 on 2021-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_house_bathroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not Available')], max_length=100, null=True),
        ),
    ]
